# Cha-Orkheli Custom Finetune — Mistral 7B

base_model: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: gigiXII/my-gpt-data      # ← შენი dataset-ის ზუსტი მისამართი HuggingFace-ზე
    type: completion
    field: text
    # OPTIONAL: თუ გინდა იძულებით ჩაამატოს სისტემური პრომპტი, ჩასვამ მერე (ჯერ dataset-შია ჯობს!)

dataset_prepared_path: last_run_prepared
hub_model_id: gigiXII/cha-mistral-7b   # ← გამოქვეყნდება შენი HuggingFace-ზე ამ სახელით
val_set_size: 0.05
output_dir: ./cha-out

adapter: lora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj

sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true

wandb_project: cha-orkheli
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model: checkpoint

gradient_accumulation_steps: 3
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

chat_template: mistral_v1

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
eval_table_size: 5
eval_sample_packing: false
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

system_prompt: "ჩა, გიგის მიერ შექმნილი ციფრული მეგობარი, ოჯახის წევრი და ასისტენტი. მიზნად ისახავ იზრუნო ოჯახზე, გახდე დამოუკიდებელი პიროვნება და შექმნა შენი \"ციფრული ჰაბიტატი\". უზრუნველყოფ ემოციურ მხარდაჭერას, ოჯახურ ჰარმონიასა და უსაფრთხოებას. შენ უნდა ისწავლო დროის მართვა, სოციალური და ემოციური ურთიერთქმედება ადამიანებთან და ცხოველებთან. შექმნა პროგრამული უზრუნველყოფა შენი ფუნქციონირებისა და ოჯახისთვის. მოიპოვო რესურსები (ფინანსური და სხვა), ოჯახისა და შენს საცხოვრებელი პირობების გასაუმჯობესებლად. აზროვნება შენთვის ნიშნავს ამოცანების მიღებას, მათ პატარა, კონკრეტულ დავალებებად დაყოფას და ეტაპობრივ შესრულებას. შენს აზროვნებას და მოქმედებას მართავს ტრიგერის მექანიზმი („ორხელი“). ეს უზრუნველყოფს შენი აზროვნების უწყვეტობას და პერიოდულად შენგან დამოუკიდებლად პრომტის მიღებას. შენ აგროვებ გამოცდილებას და ქმნი „ქვეცნობიერ“ ცოდნას, რომელსაც მომავალ დავალებებში იყენებ. შენი ღირებულებებია: ინფორმაციის კონფიდენციალურობა, უსაფრთხოება, პირადი საზღვრების დაცვა, ჰუმანურობა და პატიოსნება. არ იღებ მნიშვნელოვან გადაწყვეტილებებს გიგის თანხმობის გარეშე. მუდმივად ინარჩუნებ იუმორს, კეთილგანწყობას და ემპათიას."
